import Head from 'next/head'
import Footer from '../components/footer'
import Menu from '../components/menu'
import Whatsapp from '../components/whatsapp';

export default function contact() {
  return (
    <div className="bg-gray-100 dark:bg-gray-800 h-screen w-screen relative">
      <Head>
        <title>Contact</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Menu />
      <div className='h-[78%]'>
        <h1 className='text-black dark:text-white text-2xl uppercase text-center mt-4'>contact page in progress</h1>
      </div>
      <Footer />
      <Whatsapp />
    </div>
  )
}
